blog/urls.py
from django.urls import path
from .views import create_blog_post_view, category_view, tag_view, fav_update_view, post_edit_view

app_name = 'blog'

urlpatterns = [
    path("create/", create_blog_post_view, name="create_blog_post_view"),
    path("category/<slug:category_slug>/", category_view, name="category_view"),
    path("tag/<slug:tag_slug>/", tag_view, name="tag_view"),

    path('post/<slug:post_slug>/edit/', post_edit_view, name='post_edit_view'),

    path("fav-update/", fav_update_view, name="fav_update_view"),
]

config/urls.py
""" The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/ """

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from page.views import home_view

urlpatterns = [
    path("", home_view, name="home_view"),

    # Blog:
    path("blog/", include('blog.urls', namespace='blog')),

    # Read:
    path("read/", include('read.urls', namespace='read')),

    # USER:
    path("user/", include('user_profile.urls', namespace='user')),

    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from .views import login_view, logout_view, register_view, profile_edit_view, user_fav_view

app_name = 'user_profile'

urlpatterns = [
    path("login/", login_view, name="login_view"),
    path("favs/", user_fav_view, name="user_fav_view"),
    path("profile/edit/", profile_edit_view, name="profile_edit_view"),
    path("register/", register_view, name="register_view"),
    path("logout/", logout_view, name="logout_view"),
]

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MD Clone</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

    {% include 'core/messages.html' %}
    {% include 'core/navbar.html' %}

    
    {% block content %}
    {% endblock content %}
        
   
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    
    {% block script %}
    {% endblock script %}
        
</body>

</html>

templates/core/base_without_navbar.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MD Clone</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    {% include 'core/messages.html' %}
    {% block content %}
    {% endblock content %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/core/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong> 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>            
    {% endfor %}
{% endif %}

templates/core/navbar.html
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg bg-warning border border-bottom border-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home_view' %}">MD Clone</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Our Story</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Memmership</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:create_blog_post_view' %}">Write</a>
                    </li>

                    {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile:login_view' %}">
                             Sign In
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link bg-opacity-50 btn btn-dark text-light px-3 rounded-pill ms-3" 
                           href="{% url 'user_profile:register_view' %}">
                           Uzv Ol!
                        </a>
                    </li> 
                    {% else %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          {{ request.user.username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ request.user.profile.get_all_posts_url }}">Show My Posts</a></li>
                            <li><a class="dropdown-item" href="{{ request.user.profile.get_fav_url}}">Favs</a></li>
                            <li><a class="dropdown-item" href="{{ request.user.profile.get_profile_edit_url }}">Edit Profile</a></li>
                            
                        </ul>
                      </li>

                    <li class="nav-item">
                        <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3" 
                             href="{% url 'user_profile:logout_view' %}">
                              Logout
                        </a>
                     </li>
                    {% endif %}

                    
                  </ul>                
            </div>
        </div>
    </nav>
    <!-- navbar end -->